envVarGroups:
  # Shared environment variables for all services
  - name: email-digest-shared
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: REPLY_LINK_MODE
        value: ""
      - key: APP_PSWD
        sync: false
      - key: RENDER
        value: "true"

services:
  # TEST - Runs every 5 minutes for testing with amr
  - type: cron
    name: email-digest-test-amr
    runtime: python
    plan: starter
    schedule: "*/5 * * * *"  # Every 5 minutes
    buildCommand: pip install -r requirements.txt
    command: python main.py
    envVars:
      - fromGroup: email-digest-shared
      - key: USER_PROFILE
        value: amr
      - key: FROM_EMAIL
        value: amr@multiply.ae
      - key: TO_EMAIL
        value: amr@multiply.ae
      - key: EMAIL_FORMAT
        value: modern

  # Cron job for morning email digest (9am UAE = 5am UTC)
  - type: cron
    name: email-digest-morning-jawad
    runtime: python
    plan: starter
    schedule: "0 5 * * *"  # 5:00 AM UTC = 9:00 AM UAE
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py morning
    envVars:
      - fromGroup: email-digest-shared
      - key: USER_PROFILE
        value: jawad
      - key: FROM_EMAIL
        value: jawad@multiply.ae
      - key: TO_EMAIL
        value: jawad@multiply.ae
      - key: EMAIL_FORMAT
        value: windows

  # Cron job for afternoon email digest (2pm UAE = 10am UTC)
  - type: cron
    name: email-digest-afternoon-jawad
    runtime: python
    plan: starter
    schedule: "0 10 * * *"  # 10:00 AM UTC = 2:00 PM UAE
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py afternoon
    envVars:
      - fromGroup: email-digest-shared
      - key: USER_PROFILE
        value: jawad
      - key: FROM_EMAIL
        value: jawad@multiply.ae
      - key: TO_EMAIL
        value: jawad@multiply.ae
      - key: EMAIL_FORMAT
        value: windows